//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cscommandlets.Classifications {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:Classifications.service.livelink.opentext.com", ConfigurationName="Classifications.Classifications")]
    public interface Classifications {
        
        // CODEGEN: Generating message contract since message ApplyClassificationsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="urn:Classifications.service.livelink.opentext.com/ApplyClassifications", ReplyAction="urn:Classifications.service.livelink.opentext.com/Classifications/ApplyClassifica" +
            "tionsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceDataObject2))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceDataObject1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceDataObject))]
        cscommandlets.Classifications.ApplyClassificationsResponse ApplyClassifications(cscommandlets.Classifications.ApplyClassificationsRequest request);
        
        // CODEGEN: Generating message contract since message RemoveClassificationsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="urn:Classifications.service.livelink.opentext.com/RemoveClassifications", ReplyAction="urn:Classifications.service.livelink.opentext.com/Classifications/RemoveClassific" +
            "ationsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceDataObject2))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceDataObject1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceDataObject))]
        cscommandlets.Classifications.RemoveClassificationsResponse RemoveClassifications(cscommandlets.Classifications.RemoveClassificationsRequest request);
        
        // CODEGEN: Generating message contract since message UnClassifyRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="urn:Classifications.service.livelink.opentext.com/UnClassify", ReplyAction="urn:Classifications.service.livelink.opentext.com/Classifications/UnClassifyRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceDataObject2))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceDataObject1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceDataObject))]
        cscommandlets.Classifications.UnClassifyResponse UnClassify(cscommandlets.Classifications.UnClassifyRequest request);
        
        // CODEGEN: Generating message contract since message GetItemClassificationsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="urn:Classifications.service.livelink.opentext.com/GetItemClassifications", ReplyAction="urn:Classifications.service.livelink.opentext.com/Classifications/GetItemClassifi" +
            "cationsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceDataObject2))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceDataObject1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceDataObject))]
        cscommandlets.Classifications.GetItemClassificationsResponse GetItemClassifications(cscommandlets.Classifications.GetItemClassificationsRequest request);
        
        // CODEGEN: Generating message contract since message GetManagedTypesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="urn:Classifications.service.livelink.opentext.com/GetManagedTypes", ReplyAction="urn:Classifications.service.livelink.opentext.com/Classifications/GetManagedTypes" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceDataObject2))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceDataObject1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceDataObject))]
        cscommandlets.Classifications.GetManagedTypesResponse GetManagedTypes(cscommandlets.Classifications.GetManagedTypesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:api.ecm.opentext.com")]
    public partial class OTAuthentication : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string authenticationTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AuthenticationToken {
            get {
                return this.authenticationTokenField;
            }
            set {
                this.authenticationTokenField = value;
                this.RaisePropertyChanged("AuthenticationToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PrimitiveValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DateValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntegerValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RealValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StringValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BooleanValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TableValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RowValue))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ServiceDataObject", Namespace="urn:Core.service.livelink.opentext.com")]
    public abstract partial class ServiceDataObject2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PrimitiveValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DateValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntegerValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RealValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StringValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BooleanValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TableValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RowValue))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Core.service.livelink.opentext.com")]
    public partial class DataValue : ServiceDataObject2 {
        
        private string descriptionField;
        
        private string keyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DateValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntegerValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RealValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StringValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BooleanValue))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Core.service.livelink.opentext.com")]
    public partial class PrimitiveValue : DataValue {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Core.service.livelink.opentext.com")]
    public partial class DateValue : PrimitiveValue {
        
        private System.Nullable<System.DateTime>[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Values", IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime>[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Core.service.livelink.opentext.com")]
    public partial class IntegerValue : PrimitiveValue {
        
        private System.Nullable<int>[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Values", IsNullable=true, Order=0)]
        public System.Nullable<int>[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Core.service.livelink.opentext.com")]
    public partial class RealValue : PrimitiveValue {
        
        private System.Nullable<double>[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Values", IsNullable=true, Order=0)]
        public System.Nullable<double>[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Core.service.livelink.opentext.com")]
    public partial class StringValue : PrimitiveValue {
        
        private string[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Values", Order=0)]
        public string[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Core.service.livelink.opentext.com")]
    public partial class BooleanValue : PrimitiveValue {
        
        private System.Nullable<bool>[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Values", IsNullable=true, Order=0)]
        public System.Nullable<bool>[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Core.service.livelink.opentext.com")]
    public partial class TableValue : DataValue {
        
        private RowValue[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Values", Order=0)]
        public RowValue[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Core.service.livelink.opentext.com")]
    public partial class RowValue : DataValue {
        
        private DataValue[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Values", Order=0)]
        public DataValue[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Version))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NodeVersionInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NodeReservationInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NodeReferenceInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NodePermissions))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttributeGroup))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Metadata))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NodeFeature))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NodeContainerInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Node))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ServiceDataObject", Namespace="urn:DocMan.service.livelink.opentext.com")]
    public abstract partial class ServiceDataObject1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DocMan.service.livelink.opentext.com")]
    public partial class Version : ServiceDataObject1 {
        
        private string commentField;
        
        private System.Nullable<System.DateTime> createDateField;
        
        private System.Nullable<System.DateTime> fileCreateDateField;
        
        private string fileCreatorField;
        
        private long fileDataSizeField;
        
        private System.Nullable<System.DateTime> fileModifyDateField;
        
        private string filenameField;
        
        private int filePlatformField;
        
        private int fileResSizeField;
        
        private string fileTypeField;
        
        private int idField;
        
        private int lockedField;
        
        private System.Nullable<int> lockedByField;
        
        private System.Nullable<System.DateTime> lockedDateField;
        
        private Metadata metadataField;
        
        private string mimeTypeField;
        
        private System.Nullable<System.DateTime> modifyDateField;
        
        private string nameField;
        
        private int nodeIDField;
        
        private int numberField;
        
        private int ownerField;
        
        private int providerIDField;
        
        private string providerNameField;
        
        private string typeField;
        
        private int verMajorField;
        
        private int verMinorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("Comment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
                this.RaisePropertyChanged("CreateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> FileCreateDate {
            get {
                return this.fileCreateDateField;
            }
            set {
                this.fileCreateDateField = value;
                this.RaisePropertyChanged("FileCreateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FileCreator {
            get {
                return this.fileCreatorField;
            }
            set {
                this.fileCreatorField = value;
                this.RaisePropertyChanged("FileCreator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long FileDataSize {
            get {
                return this.fileDataSizeField;
            }
            set {
                this.fileDataSizeField = value;
                this.RaisePropertyChanged("FileDataSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> FileModifyDate {
            get {
                return this.fileModifyDateField;
            }
            set {
                this.fileModifyDateField = value;
                this.RaisePropertyChanged("FileModifyDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
                this.RaisePropertyChanged("Filename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int FilePlatform {
            get {
                return this.filePlatformField;
            }
            set {
                this.filePlatformField = value;
                this.RaisePropertyChanged("FilePlatform");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int FileResSize {
            get {
                return this.fileResSizeField;
            }
            set {
                this.fileResSizeField = value;
                this.RaisePropertyChanged("FileResSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string FileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
                this.RaisePropertyChanged("FileType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int Locked {
            get {
                return this.lockedField;
            }
            set {
                this.lockedField = value;
                this.RaisePropertyChanged("Locked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> LockedBy {
            get {
                return this.lockedByField;
            }
            set {
                this.lockedByField = value;
                this.RaisePropertyChanged("LockedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<System.DateTime> LockedDate {
            get {
                return this.lockedDateField;
            }
            set {
                this.lockedDateField = value;
                this.RaisePropertyChanged("LockedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public Metadata Metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
                this.RaisePropertyChanged("Metadata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string MimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
                this.RaisePropertyChanged("MimeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<System.DateTime> ModifyDate {
            get {
                return this.modifyDateField;
            }
            set {
                this.modifyDateField = value;
                this.RaisePropertyChanged("ModifyDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int NodeID {
            get {
                return this.nodeIDField;
            }
            set {
                this.nodeIDField = value;
                this.RaisePropertyChanged("NodeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int Owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
                this.RaisePropertyChanged("Owner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int ProviderID {
            get {
                return this.providerIDField;
            }
            set {
                this.providerIDField = value;
                this.RaisePropertyChanged("ProviderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string ProviderName {
            get {
                return this.providerNameField;
            }
            set {
                this.providerNameField = value;
                this.RaisePropertyChanged("ProviderName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public int VerMajor {
            get {
                return this.verMajorField;
            }
            set {
                this.verMajorField = value;
                this.RaisePropertyChanged("VerMajor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int VerMinor {
            get {
                return this.verMinorField;
            }
            set {
                this.verMinorField = value;
                this.RaisePropertyChanged("VerMinor");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DocMan.service.livelink.opentext.com")]
    public partial class Metadata : ServiceDataObject1 {
        
        private AttributeGroup[] attributeGroupsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttributeGroups", Order=0)]
        public AttributeGroup[] AttributeGroups {
            get {
                return this.attributeGroupsField;
            }
            set {
                this.attributeGroupsField = value;
                this.RaisePropertyChanged("AttributeGroups");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DocMan.service.livelink.opentext.com")]
    public partial class AttributeGroup : ServiceDataObject1 {
        
        private string displayNameField;
        
        private string keyField;
        
        private string typeField;
        
        private DataValue[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
                this.RaisePropertyChanged("DisplayName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Values", Order=3)]
        public DataValue[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DocMan.service.livelink.opentext.com")]
    public partial class NodeVersionInfo : ServiceDataObject1 {
        
        private bool advancedVersionControlField;
        
        private System.Nullable<long> fileDataSizeField;
        
        private System.Nullable<int> fileResSizeField;
        
        private System.Nullable<int> majorField;
        
        private string mimeTypeField;
        
        private bool supportsAdvancedVersionControlField;
        
        private int versionNumField;
        
        private Version[] versionsField;
        
        private System.Nullable<int> versionsToKeepField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool AdvancedVersionControl {
            get {
                return this.advancedVersionControlField;
            }
            set {
                this.advancedVersionControlField = value;
                this.RaisePropertyChanged("AdvancedVersionControl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<long> FileDataSize {
            get {
                return this.fileDataSizeField;
            }
            set {
                this.fileDataSizeField = value;
                this.RaisePropertyChanged("FileDataSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> FileResSize {
            get {
                return this.fileResSizeField;
            }
            set {
                this.fileResSizeField = value;
                this.RaisePropertyChanged("FileResSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> Major {
            get {
                return this.majorField;
            }
            set {
                this.majorField = value;
                this.RaisePropertyChanged("Major");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
                this.RaisePropertyChanged("MimeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool SupportsAdvancedVersionControl {
            get {
                return this.supportsAdvancedVersionControlField;
            }
            set {
                this.supportsAdvancedVersionControlField = value;
                this.RaisePropertyChanged("SupportsAdvancedVersionControl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int VersionNum {
            get {
                return this.versionNumField;
            }
            set {
                this.versionNumField = value;
                this.RaisePropertyChanged("VersionNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Versions", Order=7)]
        public Version[] Versions {
            get {
                return this.versionsField;
            }
            set {
                this.versionsField = value;
                this.RaisePropertyChanged("Versions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> VersionsToKeep {
            get {
                return this.versionsToKeepField;
            }
            set {
                this.versionsToKeepField = value;
                this.RaisePropertyChanged("VersionsToKeep");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DocMan.service.livelink.opentext.com")]
    public partial class NodeReservationInfo : ServiceDataObject1 {
        
        private bool reservedField;
        
        private int reservedByField;
        
        private System.Nullable<System.DateTime> reservedDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Reserved {
            get {
                return this.reservedField;
            }
            set {
                this.reservedField = value;
                this.RaisePropertyChanged("Reserved");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ReservedBy {
            get {
                return this.reservedByField;
            }
            set {
                this.reservedByField = value;
                this.RaisePropertyChanged("ReservedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> ReservedDate {
            get {
                return this.reservedDateField;
            }
            set {
                this.reservedDateField = value;
                this.RaisePropertyChanged("ReservedDate");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DocMan.service.livelink.opentext.com")]
    public partial class NodeReferenceInfo : ServiceDataObject1 {
        
        private int originalIDField;
        
        private string originalTypeField;
        
        private System.Nullable<int> versionNumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int OriginalID {
            get {
                return this.originalIDField;
            }
            set {
                this.originalIDField = value;
                this.RaisePropertyChanged("OriginalID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OriginalType {
            get {
                return this.originalTypeField;
            }
            set {
                this.originalTypeField = value;
                this.RaisePropertyChanged("OriginalType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> VersionNum {
            get {
                return this.versionNumField;
            }
            set {
                this.versionNumField = value;
                this.RaisePropertyChanged("VersionNum");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DocMan.service.livelink.opentext.com")]
    public partial class NodePermissions : ServiceDataObject1 {
        
        private bool addItemsPermissionField;
        
        private bool deletePermissionField;
        
        private bool deleteVersionsPermissionField;
        
        private bool editAttributesPermissionField;
        
        private bool editPermissionsPermissionField;
        
        private bool modifyPermissionField;
        
        private bool reservePermissionField;
        
        private bool seeContentsPermissionField;
        
        private bool seePermissionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool AddItemsPermission {
            get {
                return this.addItemsPermissionField;
            }
            set {
                this.addItemsPermissionField = value;
                this.RaisePropertyChanged("AddItemsPermission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool DeletePermission {
            get {
                return this.deletePermissionField;
            }
            set {
                this.deletePermissionField = value;
                this.RaisePropertyChanged("DeletePermission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool DeleteVersionsPermission {
            get {
                return this.deleteVersionsPermissionField;
            }
            set {
                this.deleteVersionsPermissionField = value;
                this.RaisePropertyChanged("DeleteVersionsPermission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool EditAttributesPermission {
            get {
                return this.editAttributesPermissionField;
            }
            set {
                this.editAttributesPermissionField = value;
                this.RaisePropertyChanged("EditAttributesPermission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool EditPermissionsPermission {
            get {
                return this.editPermissionsPermissionField;
            }
            set {
                this.editPermissionsPermissionField = value;
                this.RaisePropertyChanged("EditPermissionsPermission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool ModifyPermission {
            get {
                return this.modifyPermissionField;
            }
            set {
                this.modifyPermissionField = value;
                this.RaisePropertyChanged("ModifyPermission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool ReservePermission {
            get {
                return this.reservePermissionField;
            }
            set {
                this.reservePermissionField = value;
                this.RaisePropertyChanged("ReservePermission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool SeeContentsPermission {
            get {
                return this.seeContentsPermissionField;
            }
            set {
                this.seeContentsPermissionField = value;
                this.RaisePropertyChanged("SeeContentsPermission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool SeePermission {
            get {
                return this.seePermissionField;
            }
            set {
                this.seePermissionField = value;
                this.RaisePropertyChanged("SeePermission");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DocMan.service.livelink.opentext.com")]
    public partial class NodeFeature : ServiceDataObject1 {
        
        private System.Nullable<bool> booleanValueField;
        
        private System.Nullable<System.DateTime> dateValueField;
        
        private System.Nullable<int> integerValueField;
        
        private System.Nullable<long> longValueField;
        
        private string nameField;
        
        private string stringValueField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<bool> BooleanValue {
            get {
                return this.booleanValueField;
            }
            set {
                this.booleanValueField = value;
                this.RaisePropertyChanged("BooleanValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> DateValue {
            get {
                return this.dateValueField;
            }
            set {
                this.dateValueField = value;
                this.RaisePropertyChanged("DateValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> IntegerValue {
            get {
                return this.integerValueField;
            }
            set {
                this.integerValueField = value;
                this.RaisePropertyChanged("IntegerValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<long> LongValue {
            get {
                return this.longValueField;
            }
            set {
                this.longValueField = value;
                this.RaisePropertyChanged("LongValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string StringValue {
            get {
                return this.stringValueField;
            }
            set {
                this.stringValueField = value;
                this.RaisePropertyChanged("StringValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DocMan.service.livelink.opentext.com")]
    public partial class NodeContainerInfo : ServiceDataObject1 {
        
        private int childCountField;
        
        private string[] childTypesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ChildCount {
            get {
                return this.childCountField;
            }
            set {
                this.childCountField = value;
                this.RaisePropertyChanged("ChildCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ChildTypes", Order=1)]
        public string[] ChildTypes {
            get {
                return this.childTypesField;
            }
            set {
                this.childTypesField = value;
                this.RaisePropertyChanged("ChildTypes");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DocMan.service.livelink.opentext.com")]
    public partial class Node : ServiceDataObject1 {
        
        private System.Nullable<int> catalogField;
        
        private string commentField;
        
        private NodeContainerInfo containerInfoField;
        
        private System.Nullable<System.DateTime> createDateField;
        
        private System.Nullable<int> createdByField;
        
        private string displayTypeField;
        
        private NodeFeature[] featuresField;
        
        private int idField;
        
        private bool isContainerField;
        
        private bool isReferenceField;
        
        private bool isReservableField;
        
        private bool isVersionableField;
        
        private Metadata metadataField;
        
        private System.Nullable<System.DateTime> modifyDateField;
        
        private string nameField;
        
        private string nicknameField;
        
        private int parentIDField;
        
        private bool partialDataField;
        
        private NodePermissions permissionsField;
        
        private System.Nullable<int> positionField;
        
        private NodeReferenceInfo referenceInfoField;
        
        private bool releasedField;
        
        private NodeReservationInfo reservationInfoField;
        
        private string typeField;
        
        private NodeVersionInfo versionInfoField;
        
        private int volumeIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> Catalog {
            get {
                return this.catalogField;
            }
            set {
                this.catalogField = value;
                this.RaisePropertyChanged("Catalog");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("Comment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public NodeContainerInfo ContainerInfo {
            get {
                return this.containerInfoField;
            }
            set {
                this.containerInfoField = value;
                this.RaisePropertyChanged("ContainerInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
                this.RaisePropertyChanged("CreateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DisplayType {
            get {
                return this.displayTypeField;
            }
            set {
                this.displayTypeField = value;
                this.RaisePropertyChanged("DisplayType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Features", Order=6)]
        public NodeFeature[] Features {
            get {
                return this.featuresField;
            }
            set {
                this.featuresField = value;
                this.RaisePropertyChanged("Features");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool IsContainer {
            get {
                return this.isContainerField;
            }
            set {
                this.isContainerField = value;
                this.RaisePropertyChanged("IsContainer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool IsReference {
            get {
                return this.isReferenceField;
            }
            set {
                this.isReferenceField = value;
                this.RaisePropertyChanged("IsReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool IsReservable {
            get {
                return this.isReservableField;
            }
            set {
                this.isReservableField = value;
                this.RaisePropertyChanged("IsReservable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool IsVersionable {
            get {
                return this.isVersionableField;
            }
            set {
                this.isVersionableField = value;
                this.RaisePropertyChanged("IsVersionable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public Metadata Metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
                this.RaisePropertyChanged("Metadata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<System.DateTime> ModifyDate {
            get {
                return this.modifyDateField;
            }
            set {
                this.modifyDateField = value;
                this.RaisePropertyChanged("ModifyDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string Nickname {
            get {
                return this.nicknameField;
            }
            set {
                this.nicknameField = value;
                this.RaisePropertyChanged("Nickname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int ParentID {
            get {
                return this.parentIDField;
            }
            set {
                this.parentIDField = value;
                this.RaisePropertyChanged("ParentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool PartialData {
            get {
                return this.partialDataField;
            }
            set {
                this.partialDataField = value;
                this.RaisePropertyChanged("PartialData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public NodePermissions Permissions {
            get {
                return this.permissionsField;
            }
            set {
                this.permissionsField = value;
                this.RaisePropertyChanged("Permissions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<int> Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("Position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public NodeReferenceInfo ReferenceInfo {
            get {
                return this.referenceInfoField;
            }
            set {
                this.referenceInfoField = value;
                this.RaisePropertyChanged("ReferenceInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public bool Released {
            get {
                return this.releasedField;
            }
            set {
                this.releasedField = value;
                this.RaisePropertyChanged("Released");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public NodeReservationInfo ReservationInfo {
            get {
                return this.reservationInfoField;
            }
            set {
                this.reservationInfoField = value;
                this.RaisePropertyChanged("ReservationInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public NodeVersionInfo VersionInfo {
            get {
                return this.versionInfoField;
            }
            set {
                this.versionInfoField = value;
                this.RaisePropertyChanged("VersionInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int VolumeID {
            get {
                return this.volumeIDField;
            }
            set {
                this.volumeIDField = value;
                this.RaisePropertyChanged("VolumeID");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ManagedTypeInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClassificationInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Classifications.service.livelink.opentext.com")]
    public abstract partial class ServiceDataObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Classifications.service.livelink.opentext.com")]
    public partial class ManagedTypeInfo : ServiceDataObject {
        
        private int subTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int SubType {
            get {
                return this.subTypeField;
            }
            set {
                this.subTypeField = value;
                this.RaisePropertyChanged("SubType");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Classifications.service.livelink.opentext.com")]
    public partial class ClassificationInfo : ServiceDataObject {
        
        private Node myNodeField;
        
        private System.Nullable<bool> selectableField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Node MyNode {
            get {
                return this.myNodeField;
            }
            set {
                this.myNodeField = value;
                this.RaisePropertyChanged("MyNode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<bool> Selectable {
            get {
                return this.selectableField;
            }
            set {
                this.selectableField = value;
                this.RaisePropertyChanged("Selectable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApplyClassifications", WrapperNamespace="urn:Classifications.service.livelink.opentext.com", IsWrapped=true)]
    public partial class ApplyClassificationsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:api.ecm.opentext.com")]
        public cscommandlets.Classifications.OTAuthentication OTAuthentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Classifications.service.livelink.opentext.com", Order=0)]
        public int NodeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Classifications.service.livelink.opentext.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("ClassIDs")]
        public int[] ClassIDs;
        
        public ApplyClassificationsRequest() {
        }
        
        public ApplyClassificationsRequest(cscommandlets.Classifications.OTAuthentication OTAuthentication, int NodeID, int[] ClassIDs) {
            this.OTAuthentication = OTAuthentication;
            this.NodeID = NodeID;
            this.ClassIDs = ClassIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApplyClassificationsResponse", WrapperNamespace="urn:Classifications.service.livelink.opentext.com", IsWrapped=true)]
    public partial class ApplyClassificationsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:api.ecm.opentext.com")]
        public cscommandlets.Classifications.OTAuthentication OTAuthentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Classifications.service.livelink.opentext.com", Order=0)]
        public bool ApplyClassificationsResult;
        
        public ApplyClassificationsResponse() {
        }
        
        public ApplyClassificationsResponse(cscommandlets.Classifications.OTAuthentication OTAuthentication, bool ApplyClassificationsResult) {
            this.OTAuthentication = OTAuthentication;
            this.ApplyClassificationsResult = ApplyClassificationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveClassifications", WrapperNamespace="urn:Classifications.service.livelink.opentext.com", IsWrapped=true)]
    public partial class RemoveClassificationsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:api.ecm.opentext.com")]
        public cscommandlets.Classifications.OTAuthentication OTAuthentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Classifications.service.livelink.opentext.com", Order=0)]
        public int NodeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Classifications.service.livelink.opentext.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("secClassIDs")]
        public int[] secClassIDs;
        
        public RemoveClassificationsRequest() {
        }
        
        public RemoveClassificationsRequest(cscommandlets.Classifications.OTAuthentication OTAuthentication, int NodeID, int[] secClassIDs) {
            this.OTAuthentication = OTAuthentication;
            this.NodeID = NodeID;
            this.secClassIDs = secClassIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveClassificationsResponse", WrapperNamespace="urn:Classifications.service.livelink.opentext.com", IsWrapped=true)]
    public partial class RemoveClassificationsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:api.ecm.opentext.com")]
        public cscommandlets.Classifications.OTAuthentication OTAuthentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Classifications.service.livelink.opentext.com", Order=0)]
        public bool RemoveClassificationsResult;
        
        public RemoveClassificationsResponse() {
        }
        
        public RemoveClassificationsResponse(cscommandlets.Classifications.OTAuthentication OTAuthentication, bool RemoveClassificationsResult) {
            this.OTAuthentication = OTAuthentication;
            this.RemoveClassificationsResult = RemoveClassificationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UnClassify", WrapperNamespace="urn:Classifications.service.livelink.opentext.com", IsWrapped=true)]
    public partial class UnClassifyRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:api.ecm.opentext.com")]
        public cscommandlets.Classifications.OTAuthentication OTAuthentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Classifications.service.livelink.opentext.com", Order=0)]
        public int NodeID;
        
        public UnClassifyRequest() {
        }
        
        public UnClassifyRequest(cscommandlets.Classifications.OTAuthentication OTAuthentication, int NodeID) {
            this.OTAuthentication = OTAuthentication;
            this.NodeID = NodeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UnClassifyResponse", WrapperNamespace="urn:Classifications.service.livelink.opentext.com", IsWrapped=true)]
    public partial class UnClassifyResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:api.ecm.opentext.com")]
        public cscommandlets.Classifications.OTAuthentication OTAuthentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Classifications.service.livelink.opentext.com", Order=0)]
        public bool UnClassifyResult;
        
        public UnClassifyResponse() {
        }
        
        public UnClassifyResponse(cscommandlets.Classifications.OTAuthentication OTAuthentication, bool UnClassifyResult) {
            this.OTAuthentication = OTAuthentication;
            this.UnClassifyResult = UnClassifyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetItemClassifications", WrapperNamespace="urn:Classifications.service.livelink.opentext.com", IsWrapped=true)]
    public partial class GetItemClassificationsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:api.ecm.opentext.com")]
        public cscommandlets.Classifications.OTAuthentication OTAuthentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Classifications.service.livelink.opentext.com", Order=0)]
        public int NodeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Classifications.service.livelink.opentext.com", Order=1)]
        public bool Accepted;
        
        public GetItemClassificationsRequest() {
        }
        
        public GetItemClassificationsRequest(cscommandlets.Classifications.OTAuthentication OTAuthentication, int NodeID, bool Accepted) {
            this.OTAuthentication = OTAuthentication;
            this.NodeID = NodeID;
            this.Accepted = Accepted;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetItemClassificationsResponse", WrapperNamespace="urn:Classifications.service.livelink.opentext.com", IsWrapped=true)]
    public partial class GetItemClassificationsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:api.ecm.opentext.com")]
        public cscommandlets.Classifications.OTAuthentication OTAuthentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Classifications.service.livelink.opentext.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("GetItemClassificationsResult", IsNullable=true)]
        public cscommandlets.Classifications.ClassificationInfo[] GetItemClassificationsResult;
        
        public GetItemClassificationsResponse() {
        }
        
        public GetItemClassificationsResponse(cscommandlets.Classifications.OTAuthentication OTAuthentication, cscommandlets.Classifications.ClassificationInfo[] GetItemClassificationsResult) {
            this.OTAuthentication = OTAuthentication;
            this.GetItemClassificationsResult = GetItemClassificationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetManagedTypes", WrapperNamespace="urn:Classifications.service.livelink.opentext.com", IsWrapped=true)]
    public partial class GetManagedTypesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:api.ecm.opentext.com")]
        public cscommandlets.Classifications.OTAuthentication OTAuthentication;
        
        public GetManagedTypesRequest() {
        }
        
        public GetManagedTypesRequest(cscommandlets.Classifications.OTAuthentication OTAuthentication) {
            this.OTAuthentication = OTAuthentication;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetManagedTypesResponse", WrapperNamespace="urn:Classifications.service.livelink.opentext.com", IsWrapped=true)]
    public partial class GetManagedTypesResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:api.ecm.opentext.com")]
        public cscommandlets.Classifications.OTAuthentication OTAuthentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Classifications.service.livelink.opentext.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("GetManagedTypesResult", IsNullable=true)]
        public cscommandlets.Classifications.ManagedTypeInfo[] GetManagedTypesResult;
        
        public GetManagedTypesResponse() {
        }
        
        public GetManagedTypesResponse(cscommandlets.Classifications.OTAuthentication OTAuthentication, cscommandlets.Classifications.ManagedTypeInfo[] GetManagedTypesResult) {
            this.OTAuthentication = OTAuthentication;
            this.GetManagedTypesResult = GetManagedTypesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClassificationsChannel : cscommandlets.Classifications.Classifications, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClassificationsClient : System.ServiceModel.ClientBase<cscommandlets.Classifications.Classifications>, cscommandlets.Classifications.Classifications {
        
        public ClassificationsClient() {
        }
        
        public ClassificationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClassificationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassificationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassificationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cscommandlets.Classifications.ApplyClassificationsResponse cscommandlets.Classifications.Classifications.ApplyClassifications(cscommandlets.Classifications.ApplyClassificationsRequest request) {
            return base.Channel.ApplyClassifications(request);
        }
        
        public bool ApplyClassifications(ref cscommandlets.Classifications.OTAuthentication OTAuthentication, int NodeID, int[] ClassIDs) {
            cscommandlets.Classifications.ApplyClassificationsRequest inValue = new cscommandlets.Classifications.ApplyClassificationsRequest();
            inValue.OTAuthentication = OTAuthentication;
            inValue.NodeID = NodeID;
            inValue.ClassIDs = ClassIDs;
            cscommandlets.Classifications.ApplyClassificationsResponse retVal = ((cscommandlets.Classifications.Classifications)(this)).ApplyClassifications(inValue);
            OTAuthentication = retVal.OTAuthentication;
            return retVal.ApplyClassificationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cscommandlets.Classifications.RemoveClassificationsResponse cscommandlets.Classifications.Classifications.RemoveClassifications(cscommandlets.Classifications.RemoveClassificationsRequest request) {
            return base.Channel.RemoveClassifications(request);
        }
        
        public bool RemoveClassifications(ref cscommandlets.Classifications.OTAuthentication OTAuthentication, int NodeID, int[] secClassIDs) {
            cscommandlets.Classifications.RemoveClassificationsRequest inValue = new cscommandlets.Classifications.RemoveClassificationsRequest();
            inValue.OTAuthentication = OTAuthentication;
            inValue.NodeID = NodeID;
            inValue.secClassIDs = secClassIDs;
            cscommandlets.Classifications.RemoveClassificationsResponse retVal = ((cscommandlets.Classifications.Classifications)(this)).RemoveClassifications(inValue);
            OTAuthentication = retVal.OTAuthentication;
            return retVal.RemoveClassificationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cscommandlets.Classifications.UnClassifyResponse cscommandlets.Classifications.Classifications.UnClassify(cscommandlets.Classifications.UnClassifyRequest request) {
            return base.Channel.UnClassify(request);
        }
        
        public bool UnClassify(ref cscommandlets.Classifications.OTAuthentication OTAuthentication, int NodeID) {
            cscommandlets.Classifications.UnClassifyRequest inValue = new cscommandlets.Classifications.UnClassifyRequest();
            inValue.OTAuthentication = OTAuthentication;
            inValue.NodeID = NodeID;
            cscommandlets.Classifications.UnClassifyResponse retVal = ((cscommandlets.Classifications.Classifications)(this)).UnClassify(inValue);
            OTAuthentication = retVal.OTAuthentication;
            return retVal.UnClassifyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cscommandlets.Classifications.GetItemClassificationsResponse cscommandlets.Classifications.Classifications.GetItemClassifications(cscommandlets.Classifications.GetItemClassificationsRequest request) {
            return base.Channel.GetItemClassifications(request);
        }
        
        public cscommandlets.Classifications.ClassificationInfo[] GetItemClassifications(ref cscommandlets.Classifications.OTAuthentication OTAuthentication, int NodeID, bool Accepted) {
            cscommandlets.Classifications.GetItemClassificationsRequest inValue = new cscommandlets.Classifications.GetItemClassificationsRequest();
            inValue.OTAuthentication = OTAuthentication;
            inValue.NodeID = NodeID;
            inValue.Accepted = Accepted;
            cscommandlets.Classifications.GetItemClassificationsResponse retVal = ((cscommandlets.Classifications.Classifications)(this)).GetItemClassifications(inValue);
            OTAuthentication = retVal.OTAuthentication;
            return retVal.GetItemClassificationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cscommandlets.Classifications.GetManagedTypesResponse cscommandlets.Classifications.Classifications.GetManagedTypes(cscommandlets.Classifications.GetManagedTypesRequest request) {
            return base.Channel.GetManagedTypes(request);
        }
        
        public cscommandlets.Classifications.ManagedTypeInfo[] GetManagedTypes(ref cscommandlets.Classifications.OTAuthentication OTAuthentication) {
            cscommandlets.Classifications.GetManagedTypesRequest inValue = new cscommandlets.Classifications.GetManagedTypesRequest();
            inValue.OTAuthentication = OTAuthentication;
            cscommandlets.Classifications.GetManagedTypesResponse retVal = ((cscommandlets.Classifications.Classifications)(this)).GetManagedTypes(inValue);
            OTAuthentication = retVal.OTAuthentication;
            return retVal.GetManagedTypesResult;
        }
    }
}
