//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cscmdlets.ContentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:Core.service.livelink.opentext.com", ConfigurationName="ContentService.ContentService")]
    public interface ContentService {
        
        // CODEGEN: Generating message contract since message DownloadContentRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="urn:Core.service.livelink.opentext.com/DownloadContent", ReplyAction="urn:Core.service.livelink.opentext.com/ContentService/DownloadContentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceDataObject))]
        cscmdlets.ContentService.DownloadContentResponse DownloadContent(cscmdlets.ContentService.DownloadContentRequest request);
        
        // CODEGEN: Generating message contract since message UploadContentRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="urn:Core.service.livelink.opentext.com/UploadContent", ReplyAction="urn:Core.service.livelink.opentext.com/ContentService/UploadContentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceDataObject))]
        cscmdlets.ContentService.UploadContentResponse UploadContent(cscmdlets.ContentService.UploadContentRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:api.ecm.opentext.com")]
    public partial class OTAuthentication : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string authenticationTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AuthenticationToken {
            get {
                return this.authenticationTokenField;
            }
            set {
                this.authenticationTokenField = value;
                this.RaisePropertyChanged("AuthenticationToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FileAtts))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Core.service.livelink.opentext.com")]
    public abstract partial class ServiceDataObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Core.service.livelink.opentext.com")]
    public partial class FileAtts : ServiceDataObject {
        
        private System.Nullable<System.DateTime> createdDateField;
        
        private string fileNameField;
        
        private System.Nullable<long> fileSizeField;
        
        private System.Nullable<System.DateTime> modifiedDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
                this.RaisePropertyChanged("CreatedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<long> FileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
                this.RaisePropertyChanged("FileSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.modifiedDateField;
            }
            set {
                this.modifiedDateField = value;
                this.RaisePropertyChanged("ModifiedDate");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadContent", WrapperNamespace="urn:Core.service.livelink.opentext.com", IsWrapped=true)]
    public partial class DownloadContentRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:api.ecm.opentext.com")]
        public cscmdlets.ContentService.OTAuthentication OTAuthentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Core.service.livelink.opentext.com", Order=0)]
        public string contextID;
        
        public DownloadContentRequest() {
        }
        
        public DownloadContentRequest(cscmdlets.ContentService.OTAuthentication OTAuthentication, string contextID) {
            this.OTAuthentication = OTAuthentication;
            this.contextID = contextID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadContentResponse", WrapperNamespace="urn:Core.service.livelink.opentext.com", IsWrapped=true)]
    public partial class DownloadContentResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:api.ecm.opentext.com")]
        public cscmdlets.ContentService.OTAuthentication OTAuthentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Core.service.livelink.opentext.com", Order=0)]
        public System.IO.Stream DownloadContentResult;
        
        public DownloadContentResponse() {
        }
        
        public DownloadContentResponse(cscmdlets.ContentService.OTAuthentication OTAuthentication, System.IO.Stream DownloadContentResult) {
            this.OTAuthentication = OTAuthentication;
            this.DownloadContentResult = DownloadContentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadContent", WrapperNamespace="urn:Core.service.livelink.opentext.com", IsWrapped=true)]
    public partial class UploadContentRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:api.ecm.opentext.com")]
        public cscmdlets.ContentService.OTAuthentication OTAuthentication;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Core.service.livelink.opentext.com")]
        public string contextID;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Core.service.livelink.opentext.com")]
        public cscmdlets.ContentService.FileAtts fileAtts;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Core.service.livelink.opentext.com", Order=0)]
        public System.IO.Stream contents;
        
        public UploadContentRequest() {
        }
        
        public UploadContentRequest(cscmdlets.ContentService.OTAuthentication OTAuthentication, string contextID, cscmdlets.ContentService.FileAtts fileAtts, System.IO.Stream contents) {
            this.OTAuthentication = OTAuthentication;
            this.contextID = contextID;
            this.fileAtts = fileAtts;
            this.contents = contents;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadContentResponse", WrapperNamespace="urn:Core.service.livelink.opentext.com", IsWrapped=true)]
    public partial class UploadContentResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:api.ecm.opentext.com")]
        public cscmdlets.ContentService.OTAuthentication OTAuthentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Core.service.livelink.opentext.com", Order=0)]
        public string UploadContentResult;
        
        public UploadContentResponse() {
        }
        
        public UploadContentResponse(cscmdlets.ContentService.OTAuthentication OTAuthentication, string UploadContentResult) {
            this.OTAuthentication = OTAuthentication;
            this.UploadContentResult = UploadContentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ContentServiceChannel : cscmdlets.ContentService.ContentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContentServiceClient : System.ServiceModel.ClientBase<cscmdlets.ContentService.ContentService>, cscmdlets.ContentService.ContentService {
        
        public ContentServiceClient() {
        }
        
        public ContentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cscmdlets.ContentService.DownloadContentResponse cscmdlets.ContentService.ContentService.DownloadContent(cscmdlets.ContentService.DownloadContentRequest request) {
            return base.Channel.DownloadContent(request);
        }
        
        public System.IO.Stream DownloadContent(ref cscmdlets.ContentService.OTAuthentication OTAuthentication, string contextID) {
            cscmdlets.ContentService.DownloadContentRequest inValue = new cscmdlets.ContentService.DownloadContentRequest();
            inValue.OTAuthentication = OTAuthentication;
            inValue.contextID = contextID;
            cscmdlets.ContentService.DownloadContentResponse retVal = ((cscmdlets.ContentService.ContentService)(this)).DownloadContent(inValue);
            OTAuthentication = retVal.OTAuthentication;
            return retVal.DownloadContentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cscmdlets.ContentService.UploadContentResponse cscmdlets.ContentService.ContentService.UploadContent(cscmdlets.ContentService.UploadContentRequest request) {
            return base.Channel.UploadContent(request);
        }
        
        public string UploadContent(ref cscmdlets.ContentService.OTAuthentication OTAuthentication, string contextID, cscmdlets.ContentService.FileAtts fileAtts, System.IO.Stream contents) {
            cscmdlets.ContentService.UploadContentRequest inValue = new cscmdlets.ContentService.UploadContentRequest();
            inValue.OTAuthentication = OTAuthentication;
            inValue.contextID = contextID;
            inValue.fileAtts = fileAtts;
            inValue.contents = contents;
            cscmdlets.ContentService.UploadContentResponse retVal = ((cscmdlets.ContentService.ContentService)(this)).UploadContent(inValue);
            OTAuthentication = retVal.OTAuthentication;
            return retVal.UploadContentResult;
        }
    }
}
